---

- include: install_debian.yml
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
- include: hostconfig.yml
- include: acls.yml
- include: passwords.yml
- include: serverconfig.yml
